### ISSUE TITLE
For better performance in the future make sure to make a structure of data and read write that structure :)

### ISSUE THREAD

**Issue by themaoci** [voidzero-development/CSGO-External-CSharp#1]
https://raw.githubusercontent.com/faruktoptas/c-examples/master/read-write-struct.c - idea in c but who cares ...

**Comment by voidzero666** [comment]
I wrote this as an example for someone new to gamehacking, im aware how to write a struct
Theres no reason to do this externally anyway as you can simply hook clientmode  at postScreenEffect and apply your glow there or even better hook modelRender at DME and draw chams.

struct GlowObject {

    Entity* entity;

    Vector glowColor;

    float glowAlpha;

    bool glowAlphaCappedByRenderAlpha;

    float glowAlphaFunctionOfMaxVelocity;

    float glowAlphaMax;

    float glowPulseOverdrive;

    bool renderWhenOccluded;

    bool renderWhenUnoccluded;

    bool fullBloomRender;

    int fullBloomStencilTestValue;

    int glowStyle;

    int splitScreenSlot;

    int nextFreeSlot;

};
